### ISSUE TITLE
Getting keys for other ipadOS version

### ISSUE THREAD

**Issue by leocg** [MicalShow/iPad6-3-Firmwarekeys#1]
Hi, thanks for your effort generating keys for iPad6,3 hardware. I'm looking forward to get the keys for other versions, because I don't have shsh blobs for the versions you release.

Would you mind sharing how you get these keys, I'm willing to keep a MacBook always on getting ipsw keys. I tried to dump using ipwndfu fork with s8001 support (https://github.com/dora2-iOS/ipwndfu/tree/feature/dora2-ios/s8001), can get into PWNed state with checkm8 but cannot use ipsw_keys.py (https://github.com/nicolas17/ipsw_keys) to dump the firmware keys. It won't work with Dora's fork and when I try to run with original ipwndfu it won't find the usbexec.platform for the device

```
Found: CPID: 8001 CPRV: 10 CPFM: 01 SCEP: 01 BDID: 08 ECID: XXXXXXXXX IBFL: 0C SRTG: [iBoot-2481.0.0.2.1] PWD: [checkm8]
Reading manifest...
Reading keys...
CPID: 8001 CPRV: 10 CPFM: 01 SCEP: 01 BDID: 08 ECID: XXXXXXX IBFL: 0C SRTG: [iBoot-2481.0.0.2.1] PiND: [checkm8]
ERROR: No matching usbexec.platform found for this device.
```

Did you use this method in order to dump keys?

**Comment by MicalShow** [comment]
firmware key decryption tutorial
 This tutorial needs a Mac computer to complete. Linux has not been tested, and it is not suitable for ordinary users. It is only used to supplement iPhonewiki’s lack of firmware Firmware key, which makes it impossible to use futurerestore to restore the corresponding firmware model. Ordinary users should not be curious, and I will not  Answers to common users' questions about this tutorial!
 First make sure that the computer has python and pyimg4 dependencies installed, then run pyimg4 on the terminal to check if there is any output, and if so, you can perform the next operation.
 The second step is to decompress the ipsw firmware package of the system version you want to decrypt. You can directly use the archive utility to open it, and then unpack it. In the Firmware/all_flash directory, find the three img4 extensions with the words LLB, IBOOT, and SEP  file, copy it to the working directory you created, and then find the two im4p files beginning with iBEC and iBESS in the Firmware/dfu directory, and copy them to the working directory you created.
 The third step is to open the terminal, cd to the working directory you created, enter the command 'pyimg4 im4p info -i full name of the file in im4p format' and press Enter to get the output, copy the IV and KEY output of PRODUCTION under the Keybag for backup, and other im4p  The file uses this command to read iv and key in turn.
 Step 4: After reading, put your device into DFU mode, run ./gaster pwn to make the device enter cracked Pwndfu mode, and then enter the command ./gaster decrypt_kbag just saved IV+key (note the order, enter IV first and then  Enter Key, there is no space between IV and key, just connect it), press Enter to use the device CPU to decrypt iv and key, this is the firmware key we need, and then process other IV and Key in the same way until the processing is completed.
 At this point we have completed the decryption of the Firmware key.

**Comment by leocg** [comment]
Thanks, it worked! Got some firmware keys for the versions I have blobs. Will send a pull request if you want to update.

I made a new account request to iPhone wiki in order to update firmware information and test with futurerestore.
